### ISSUE TITLE
How can i get your blog theme?

### ISSUE THREAD

**Issue by ghost** [cykerway/cykerway.github.com#1]
Your blog theme is very fancy to me. Could you tell me how to build a similar one?

**Comment by cykerway** [comment]
It is a handcrafted CSS file whose link is directly embedded on the page. But unfortunately it is copyrighted and I'm not expecting anyone else to simply copy-paste and use it on their own site. There are many free alternatives on the Internet, and I doubt if anyone would be interested in buying this specific one, so there is currently no link for payment. If you really want this one, you could leave an email address below and I may send you a link for payment. If instead you just want to learn how to build a similar one, there are tons of CSS tutorials online. Some good ones I found are:

-   https://www.w3schools.com/css/
-   https://www.tutorialspoint.com/css/index.htm
-   https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps

This theme targets simplicity and expressiveness and it has nothing fancier than the tutorial examples above.

**Comment by ghost** [comment]
Thanks for your recommendations , I will try to learn CSS. These days, I had found that hugo is easy to build a custom theme. I am going to make a simple hugo theme as fancy as your's.
